# -*- coding: utf-8 -*-
"""Simulador.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-vF0ch72f8R0qv5yE27VzBZH0-R8nhCP

# **Simulador com apenas 1 caixa:**
"""

import math
import numpy as np

tipo = 0
TEC = 0
TS = 0
id = 0
e = math.e

media_fila = []
media_serviço = []
media_sistema = []
media_ocioso = []

limite = 1800

media_media_fila = 0
media_media_serviço = 0
media_media_sistema = 0
media_media_ocioso = 0

desvio_fila = 0
desvio_serviço = 0
desvio_sistema = 0
desvio_ocioso = 0

superior_fila = 0
inferior_fila = 0
superior_serviço = 0
inferior_serviço = 0
superior_sistema = 0
inferior_sistema = 0
superior_ocioso = 0
inferior_ocioso = 0

n_sementes = 499
#semente = 10
iterações = 20000

#Altere aqui os valores de a, c e M
a = 16807
c = 0
M = (2 ** 31) - 1


def random_interno(a,c,M):
    global semente
    semente = (a * semente + c) % M
    numero = semente / M
    return numero

def gera_tipo():
    global random_interno,a,c,M
    numero = random_interno(a,c,M)
    if numero < 0.1:
      return 3
    elif numero < 0.7:
      return 1
    else:
      return 2

def gera_tempos(tipo):
    global random_interno,a,c,M
    global TEC, TS
    #tempo de chegada
    TEC = -15 * math.log(random_interno(a,c,M))
    if tipo == 1:
      TS = -15 * math.log(random_interno(a,c,M)) + 15
      TS
    if tipo == 2:
      TS = -40 * math.log(random_interno(a,c,M)) + 30
    if tipo == 3:
      TS = -140 * math.log(random_interno(a,c,M)) + 60

def cria_tabela():
  global tipo, TEC, TS, id, tabela, limite
  id += 1
  linha = np.empty(10)
  linha[0] = id #0 Cliente
  linha[1] = tipo #1 Tipo
  linha[2] = TEC #2 TEC
  linha[3] = TS #3 TS
  if id != 1:
    if (TEC + tabela[id-2][4]) > limite:
      return 0

  #4 Tempo relógio
  if id == 1:
    linha[4] = TEC
  else:
    linha[4] = TEC + tabela[id-2][4]

  #5 Tempo início serviço
  if id == 1:
    linha[5] = TEC
  elif linha[4] <= tabela[id-2][6]:
    linha[5] = tabela[id-2][6]
  else:
    linha[5] = linha[4]

  #6 Tempo fim serviço
  linha[6] = linha[5] + TS

  #7 Tempo na fila
  linha[7] = linha[5] - linha[4]

  #8 Tempo no sistema
  linha[8] = linha[7] + TS

  #9 Tempo ocioso do caixa
  if id == 1:
    linha[9] = linha[5]
  else:
    linha[9] = linha[5] - tabela[id-2][6]

  tabela = np.vstack((tabela,linha))
  return 1

def calcula_media():
  global tabela
  global media_fila, media_serviço , media_sistema, media_ocioso
  media = 0
  tamanho = tabela.size // 10
  #media fila
  for i in range(tamanho):
    media += tabela[i][7]
  media /= tamanho
  media_fila.append(media)
  media = 0
  #media serviço
  for i in range(tamanho):
    media += tabela[i][3]
  media /= tamanho
  media_serviço.append(media)
  media = 0
  #media sistema
  for i in range(tamanho):
    media += tabela[i][8]
  media /= tamanho
  media_sistema.append(media)
  media = 0
  #media ocioso
  for i in range(tamanho):
    media += tabela[i][9]
  media /= tamanho
  media_ocioso.append(media)

def media_media():
  global media_fila, media_serviço , media_sistema, media_ocioso
  global media_media_fila, media_media_serviço , media_media_sistema, media_media_ocioso
  global desvio_fila, desvio_serviço, desvio_sistema, desvio_ocioso

  for i in range(len(media_fila)):
    media_media_fila += media_fila[i]
  media_media_fila /= len(media_fila)
  for i in range(len(media_fila)):
    desvio_fila += (media_fila[i] - media_media_fila) ** 2
  desvio_fila /= len(media_fila) - 1
  desvio_fila = math.sqrt(desvio_fila)

  for i in range(len(media_serviço)):
    media_media_serviço += media_serviço[i]
  media_media_serviço /= len(media_serviço)
  for i in range(len(media_serviço)):
    desvio_serviço += (media_serviço[i] - media_media_serviço) ** 2
  desvio_serviço /= len(media_serviço) - 1
  desvio_serviço = math.sqrt(desvio_serviço)

  for i in range(len(media_sistema)):
    media_media_sistema += media_sistema[i]
  media_media_sistema /= len(media_sistema)
  for i in range(len(media_sistema)):
    desvio_sistema += (media_sistema[i] - media_media_sistema) ** 2
  desvio_sistema /= len(media_sistema) - 1
  desvio_sistema = math.sqrt(desvio_sistema)

  for i in range(len(media_ocioso)):
    media_media_ocioso += media_ocioso[i]
  media_media_ocioso /= len(media_ocioso)
  for i in range(len(media_ocioso)):
    desvio_ocioso += (media_ocioso[i] - media_media_ocioso) ** 2
  desvio_ocioso /= len(media_ocioso) - 1
  desvio_ocioso = math.sqrt(desvio_ocioso)

def calcula_intervalo():
  global media_media_fila, media_media_serviço , media_media_sistema, media_media_ocioso
  global desvio_fila, desvio_serviço, desvio_sistema, desvio_ocioso
  global superior_fila, inferior_fila, superior_serviço, inferior_serviço, superior_sistema, inferior_sistema, superior_ocioso, inferior_ocioso

  inferior_fila = media_media_fila - (1.96 * (desvio_fila / math.sqrt(n_sementes)))
  superior_fila = media_media_fila + (1.96 * (desvio_fila / math.sqrt(n_sementes)))

  inferior_serviço = media_media_serviço - (1.96 * (desvio_serviço / math.sqrt(n_sementes)))
  superior_serviço = media_media_serviço + (1.96 * (desvio_serviço / math.sqrt(n_sementes)))

  inferior_sistema = media_media_sistema - (1.96 * (desvio_sistema / math.sqrt(n_sementes)))
  superior_sistema = media_media_sistema + (1.96 * (desvio_sistema / math.sqrt(n_sementes)))

  inferior_ocioso = media_media_ocioso - (1.96 * (desvio_ocioso / math.sqrt(n_sementes)))
  superior_ocioso = media_media_ocioso + (1.96 * (desvio_ocioso / math.sqrt(n_sementes)))

#MAIN
for i in range(1,n_sementes+1):
  semente = i
  random_interno(a,c,M) #ignora primeiro valor aleatório gerado
  random_interno(a,c,M) #ignora segundo valor aleatório gerado
  aberto = 1
  id = 0
  tabela = np.empty((0,10))
  while aberto:
        tipo = gera_tipo()
        gera_tempos(tipo)
        aberto = cria_tabela()
  calcula_media()

media_media()
calcula_intervalo()

print('Tempo médio gasto na fila =', media_fila)
print('Tempo médio de serviço =', media_serviço)
print('Tempo médio despendido no sistema =', media_sistema)
print('Tempo médio ocioso do sistema =', media_ocioso)
print()

print('Média das médias do tempo gasto na fila =', media_media_fila)
print('Média das médias do tempo de serviço =', media_media_serviço)
print('Média das médias do tempo despendido no sistema =', media_media_sistema)
print('Média das médias do tempo ocioso do sistema =', media_media_ocioso)
print()

print('Desvio padrão do tempo gasto na fila =', desvio_fila)
print('Desvio padrão do tempo de serviço =', desvio_serviço)
print('Desvio padrão do tempo despendido no sistema =', desvio_sistema)
print('Desvio padrão do tempo ocioso do sistema =', desvio_ocioso)
print()

print(f'Intervalo de confiança para o tempo gasto na fila = [{inferior_fila},{superior_fila}]')
print(f'Intervalo de confiança para o tempo de serviço = [{inferior_serviço},{superior_serviço}]')
print(f'Intervalo de confiança para o tempo despendido no sistema = [{inferior_sistema},{superior_sistema}]')
print(f'Intervalo de confiança para o tempo ocioso do sistema = [{inferior_ocioso},{superior_ocioso}]')

"""# **Simulador com n caixas**"""

import math
import numpy as np

tipo = 0
TEC = 0
TS = 0
id = 0
e = math.e
n_caixas = 4
tempo_caixa = np.zeros(n_caixas)
ocioso_caixa = np.zeros(n_caixas)

media_fila = []
media_serviço = []
media_sistema = []
media_ocioso = []

limite = 21600

media_media_fila = 0
media_media_serviço = 0
media_media_sistema = 0
media_media_ocioso = 0

desvio_fila = 0
desvio_serviço = 0
desvio_sistema = 0
desvio_ocioso = 0

superior_fila = 0
inferior_fila = 0
superior_serviço = 0
inferior_serviço = 0
superior_sistema = 0
inferior_sistema = 0
superior_ocioso = 0
inferior_ocioso = 0

n_sementes = 499
#semente = 10
iterações = 20000

#Altere aqui os valores de a, c e M
a = 16807
c = 0
M = (2 ** 31) - 1

def random_interno(a,c,M):
    global semente
    semente = (a * semente + c) % M
    numero = semente / M
    return numero

def gera_tipo():
    global random_interno,a,c,M
    numero = random_interno(a,c,M)
    if numero < 0.1:
      return 3
    elif numero < 0.7:
      return 1
    else:
      return 2

def gera_tempos(tipo):
    global random_interno,a,c,M
    global TEC, TS
    #tempo de chegada
    TEC = -15 * math.log(random_interno(a,c,M))
    if tipo == 1:
      TS = -15 * math.log(random_interno(a,c,M)) + 15
      TS
    if tipo == 2:
      TS = -40 * math.log(random_interno(a,c,M)) + 30
    if tipo == 3:
      TS = -140 * math.log(random_interno(a,c,M)) + 60

def menor_valor(tempo_caixa):
    menor = 99999999999999
    pos = 0
    for i in range(len(tempo_caixa)):
      if(tempo_caixa[i] < menor):
        menor = tempo_caixa[i]
        pos = i
    return pos


def cria_tabela():
  global tipo, TEC, TS, id, tabela, limite, tempo_caixa, ocioso_caixa

  id += 1
  linha = np.empty(9)
  linha[0] = id #0 Cliente
  linha[1] = tipo #1 Tipo
  linha[2] = TEC #2 TEC
  linha[3] = TS #3 TS
  if id != 1:
    if (TEC + tabela[id-2][4]) > limite:
      return 0

  #4 Tempo de chegada no relógio
  if id == 1:
    linha[4] = TEC
  else:
    linha[4] = TEC + tabela[id-2][4]

  #5 Tempo início serviço
  if id <= n_caixas:
    caixa = id - 1
    linha[5] = linha[4]
  else:
    tem_livre = False
    for i in range(n_caixas):
      #Se houver caixas livres
      if linha[4] >= tempo_caixa[i]:
        linha[5] = linha[4]
        caixa = i
        tem_livre = True
        break
    if not tem_livre:
      caixa = menor_valor(tempo_caixa)
      linha[5] = tempo_caixa[caixa]

  #Tempo ocioso do caixa (geral)
  ocioso_caixa[caixa] += linha[5] - tempo_caixa[caixa]

  #6 Tempo fim serviço
  tempo_caixa[caixa] = linha[6] = linha[5] + TS

  #7 Tempo na fila
  linha[7] = linha[5] - linha[4]

  #8 Tempo no sistema
  linha[8] = linha[7] + TS

  tabela = np.vstack((tabela,linha))
  return 1

def calcula_media():
  global tabela
  global media_fila, media_serviço , media_sistema, media_ocioso
  media = 0
  tamanho = tabela.size // 9
  #media fila
  for i in range(tamanho):
    media += tabela[i][7]
  media /= tamanho
  media_fila.append(media)
  media = 0
  #media serviço
  for i in range(tamanho):
    media += tabela[i][3]
  media /= tamanho
  media_serviço.append(media)
  media = 0
  #media sistema
  for i in range(tamanho):
    media += tabela[i][8]
  media /= tamanho
  media_sistema.append(media)
  media = 0
  #media ocioso
  for i in range(n_caixas):
    media += ocioso_caixa[i]
  media /= (tamanho * n_caixas)
  media_ocioso.append(media)
  media = 0

def media_media():
  global media_fila, media_serviço , media_sistema, media_ocioso
  global media_media_fila, media_media_serviço , media_media_sistema, media_media_ocioso
  global desvio_fila, desvio_serviço, desvio_sistema, desvio_ocioso

  for i in range(len(media_fila)):
    media_media_fila += media_fila[i]
  media_media_fila /= len(media_fila)
  for i in range(len(media_fila)):
    desvio_fila += (media_fila[i] - media_media_fila) ** 2
  desvio_fila /= len(media_fila) - 1
  desvio_fila = math.sqrt(desvio_fila)

  for i in range(len(media_serviço)):
    media_media_serviço += media_serviço[i]
  media_media_serviço /= len(media_serviço)
  for i in range(len(media_serviço)):
    desvio_serviço += (media_serviço[i] - media_media_serviço) ** 2
  desvio_serviço /= len(media_serviço) - 1
  desvio_serviço = math.sqrt(desvio_serviço)

  for i in range(len(media_sistema)):
    media_media_sistema += media_sistema[i]
  media_media_sistema /= len(media_sistema)
  for i in range(len(media_sistema)):
    desvio_sistema += (media_sistema[i] - media_media_sistema) ** 2
  desvio_sistema /= len(media_sistema) - 1
  desvio_sistema = math.sqrt(desvio_sistema)

  for i in range(len(media_ocioso)):
    media_media_ocioso += media_ocioso[i]
  media_media_ocioso /= len(media_ocioso)
  for i in range(len(media_ocioso)):
    desvio_ocioso += (media_ocioso[i] - media_media_ocioso) ** 2
  desvio_ocioso /= len(media_ocioso) - 1
  desvio_ocioso = math.sqrt(desvio_ocioso)

def calcula_intervalo():
  global media_media_fila, media_media_serviço , media_media_sistema, media_media_ocioso
  global desvio_fila, desvio_serviço, desvio_sistema, desvio_ocioso
  global superior_fila, inferior_fila, superior_serviço, inferior_serviço, superior_sistema, inferior_sistema, superior_ocioso, inferior_ocioso

  inferior_fila = media_media_fila - (1.96 * (desvio_fila / math.sqrt(n_sementes)))
  superior_fila = media_media_fila + (1.96 * (desvio_fila / math.sqrt(n_sementes)))

  inferior_serviço = media_media_serviço - (1.96 * (desvio_serviço / math.sqrt(n_sementes)))
  superior_serviço = media_media_serviço + (1.96 * (desvio_serviço / math.sqrt(n_sementes)))

  inferior_sistema = media_media_sistema - (1.96 * (desvio_sistema / math.sqrt(n_sementes)))
  superior_sistema = media_media_sistema + (1.96 * (desvio_sistema / math.sqrt(n_sementes)))

  inferior_ocioso = media_media_ocioso - (1.96 * (desvio_ocioso / math.sqrt(n_sementes)))
  superior_ocioso = media_media_ocioso + (1.96 * (desvio_ocioso / math.sqrt(n_sementes)))

#MAIN
for i in range(1,n_sementes+1):
  semente = i
  random_interno(a,c,M) #ignora primeiro valor aleatório gerado
  random_interno(a,c,M) #ignora segundo valor aleatório gerado
  aberto = 1
  id = 0
  tabela = np.empty((0,9))
  while aberto:
        tipo = gera_tipo()
        gera_tempos(tipo)
        aberto = cria_tabela()
  calcula_media()
  for i in range(len(tempo_caixa)):
    tempo_caixa[i] = 0
    ocioso_caixa[i] = 0

media_media()
calcula_intervalo()

print('Tempo médio gasto na fila =', media_fila)
print('Tempo médio de serviço =', media_serviço)
print('Tempo médio despendido no sistema =', media_sistema)
print('Tempo médio ocioso do sistema =', media_ocioso)
print()

print('Média das médias do tempo gasto na fila =', media_media_fila)
print('Média das médias do tempo de serviço =', media_media_serviço)
print('Média das médias do tempo despendido no sistema =', media_media_sistema)
print('Média das médias do tempo ocioso do sistema =', media_media_ocioso)
print()

print('Desvio padrão do tempo gasto na fila =', desvio_fila)
print('Desvio padrão do tempo de serviço =', desvio_serviço)
print('Desvio padrão do tempo despendido no sistema =', desvio_sistema)
print('Desvio padrão do tempo ocioso do sistema =', desvio_ocioso)
print()

print(f'Intervalo de confiança para o tempo gasto na fila = [{inferior_fila},{superior_fila}]')
print(f'Intervalo de confiança para o tempo de serviço = [{inferior_serviço},{superior_serviço}]')
print(f'Intervalo de confiança para o tempo despendido no sistema = [{inferior_sistema},{superior_sistema}]')
print(f'Intervalo de confiança para o tempo ocioso do sistema = [{inferior_ocioso},{superior_ocioso}]')

"""# **Refatorada**"""

import math
import numpy as np

n_caixas = 4
tempo_simulado = 7200
n_sementes = 499

#Valores de a, c e M para o gerador de numeros pseudo-aleatórios
a = 16807
c = 0
M = (2 ** 31) - 1


#Declaração de variáveis globais
tempo_chegada = 0     #Tempo de Chegada
tempo_serviço = 0      #Tempo de Serviço
id = 0      #ID
tempo_caixa = np.zeros(n_caixas)  #Tempo do fim do ultimo serviço de cada caixa
ocioso_caixa = np.zeros(n_caixas) #Tempo em que cada caixa ficou ocioso

#Declaração do Array de médias de cada semente
media_fila = []
media_serviço = []
media_sistema = []
media_ocioso = []

#Declaração das medias das médias para cada valor necessário
media_media_fila = 0
media_media_serviço = 0
media_media_sistema = 0
media_media_ocioso = 0

#Declaração do desvio padrão dos valores necessários
desvio_fila = 0
desvio_serviço = 0
desvio_sistema = 0
desvio_ocioso = 0

#Declaração dos valores limites dos valores que serão calculados
superior_fila = 0
inferior_fila = 0
superior_serviço = 0
inferior_serviço = 0
superior_sistema = 0
inferior_sistema = 0
superior_ocioso = 0
inferior_ocioso = 0

#Função que gera numero pseudo-aleatórios
def random():
    global semente, a, c, M
    semente = (a * semente + c) % M
    numero = semente / M
    return numero

#Função que gera um tipo de cliente aleatóriamente
def gera_tipo():
    numero = random()
    if numero < 0.1:
      return 3
    elif numero < 0.7:
      return 1
    else:
      return 2
#Função que gera o tempo de chegada e tempo de serviço de acordo com um numero aleatório
def gera_tempos(tipo):
    global tempo_chegada, tempo_serviço
    #Tempo de chegada
    tempo_chegada = -15 * math.log(random())
    if tipo == 1:
      tempo_serviço = -15 * math.log(random()) + 15 #Tempo de Serviço
    if tipo == 2:
      tempo_serviço = -40 * math.log(random()) + 30
    if tipo == 3:
      tempo_serviço = -140 * math.log(random()) + 60

#Função que pega o menor valor de fim de serviço de cada caixa e devolve a posição do menor
def menor_tempo(tempo_caixa):
    menor = (2 ** 64) - 1
    pos = 0
    for i in range(len(tempo_caixa)):
      if(tempo_caixa[i] < menor):
        menor = tempo_caixa[i]
        pos = i
    return pos

#Função que cria uma tabela com todos os valores necessários para a simulação
def cria_tabela(tipo):
  global  tempo_chegada, tempo_serviço, id, tabela, limite, tempo_caixa, ocioso_caixa

  id += 1
  linha = np.empty(9)
  linha[0] = id #0 Cliente
  linha[1] = tipo #1 Tipo
  linha[2] = tempo_chegada #2 tempo_chegada
  linha[3] = tempo_serviço #3 tempo_serviço
  if id != 1:
    if (tempo_chegada + tabela[id-2][4]) > tempo_simulado:
      return 0

  #4 Tempo de chegada no relógio
  if id == 1:
    linha[4] = tempo_chegada
  else:
    linha[4] = tempo_chegada + tabela[id-2][4]

  #5 Tempo início serviço
  if id <= n_caixas:
    caixa = id - 1
    linha[5] = linha[4]
  else:
    tem_livre = False
    for i in range(n_caixas):
      #Se houver caixas livres
      if linha[4] >= tempo_caixa[i]:
        linha[5] = linha[4]
        caixa = i
        tem_livre = True
        break
    if not tem_livre:
      caixa = menor_tempo(tempo_caixa)
      linha[5] = tempo_caixa[caixa]

  #Tempo ocioso do caixa (geral)
  ocioso_caixa[caixa] += linha[5] - tempo_caixa[caixa]

  #6 Tempo fim serviço
  tempo_caixa[caixa] = linha[6] = linha[5] + tempo_serviço

  #7 Tempo na fila
  linha[7] = linha[5] - linha[4]

  #8 Tempo no sistema
  linha[8] = linha[7] + tempo_serviço

  tabela = np.vstack((tabela,linha))
  return 1

#Função que calcula a média dos valores gerados em cada tabela
def calcula_media():
  global tabela
  global media_fila, media_serviço , media_sistema, media_ocioso
  media = 0
  tamanho = tabela.size // 9    # O numero de linhas é o tamanho (linha * colunas) / colunas

  # Media fila
  for i in range(tamanho):
    media += tabela[i][7]
  media /= tamanho
  media_fila.append(media)
  media = 0

  # Media serviço
  for i in range(tamanho):
    media += tabela[i][3]
  media /= tamanho
  media_serviço.append(media)
  media = 0

  # Media sistema
  for i in range(tamanho):
    media += tabela[i][8]
  media /= tamanho
  media_sistema.append(media)
  media = 0

  # Media tempo ocioso
  for i in range(n_caixas):
    media += ocioso_caixa[i]
  media /= (tamanho * n_caixas)
  media_ocioso.append(media)
  media = 0

#Função que calcula a média das médias geradas anteriormente alem do desvio padrão das medias
def media_media_desvio():
  global media_fila, media_serviço , media_sistema, media_ocioso
  global media_media_fila, media_media_serviço , media_media_sistema, media_media_ocioso
  global desvio_fila, desvio_serviço, desvio_sistema, desvio_ocioso

  # Fila
  for i in range(len(media_fila)):
    media_media_fila += media_fila[i]
  media_media_fila /= len(media_fila)
  for i in range(len(media_fila)):
    desvio_fila += (media_fila[i] - media_media_fila) ** 2
  desvio_fila /= len(media_fila) - 1
  desvio_fila = math.sqrt(desvio_fila)

  # Serviço
  for i in range(len(media_serviço)):
    media_media_serviço += media_serviço[i]
  media_media_serviço /= len(media_serviço)
  for i in range(len(media_serviço)):
    desvio_serviço += (media_serviço[i] - media_media_serviço) ** 2
  desvio_serviço /= len(media_serviço) - 1
  desvio_serviço = math.sqrt(desvio_serviço)

  # Sistema
  for i in range(len(media_sistema)):
    media_media_sistema += media_sistema[i]
  media_media_sistema /= len(media_sistema)
  for i in range(len(media_sistema)):
    desvio_sistema += (media_sistema[i] - media_media_sistema) ** 2
  desvio_sistema /= len(media_sistema) - 1
  desvio_sistema = math.sqrt(desvio_sistema)

  # Tempo ocioso
  for i in range(len(media_ocioso)):
    media_media_ocioso += media_ocioso[i]
  media_media_ocioso /= len(media_ocioso)
  for i in range(len(media_ocioso)):
    desvio_ocioso += (media_ocioso[i] - media_media_ocioso) ** 2
  desvio_ocioso /= len(media_ocioso) - 1
  desvio_ocioso = math.sqrt(desvio_ocioso)

#Função que calcula o intervalo de confiança para cada um dos valores
def calcula_intervalo():
  global media_media_fila, media_media_serviço , media_media_sistema, media_media_ocioso
  global desvio_fila, desvio_serviço, desvio_sistema, desvio_ocioso
  global superior_fila, inferior_fila, superior_serviço, inferior_serviço, superior_sistema, inferior_sistema, superior_ocioso, inferior_ocioso

  # Fila
  inferior_fila = media_media_fila - (1.96 * (desvio_fila / math.sqrt(n_sementes)))
  superior_fila = media_media_fila + (1.96 * (desvio_fila / math.sqrt(n_sementes)))

  # Serviço
  inferior_serviço = media_media_serviço - (1.96 * (desvio_serviço / math.sqrt(n_sementes)))
  superior_serviço = media_media_serviço + (1.96 * (desvio_serviço / math.sqrt(n_sementes)))

  #Sistema
  inferior_sistema = media_media_sistema - (1.96 * (desvio_sistema / math.sqrt(n_sementes)))
  superior_sistema = media_media_sistema + (1.96 * (desvio_sistema / math.sqrt(n_sementes)))

  #Tempo Ocioso
  inferior_ocioso = media_media_ocioso - (1.96 * (desvio_ocioso / math.sqrt(n_sementes)))
  superior_ocioso = media_media_ocioso + (1.96 * (desvio_ocioso / math.sqrt(n_sementes)))

#MAIN

for i in range(1,n_sementes+1): #Utiliza um valor diferente de semente para cada iteração
  semente = i
  random() #ignora primeiro valor aleatório gerado
  random() #ignora segundo valor aleatório gerado
  aberto = 1
  id = 0
  tabela = np.empty((0,9))    #Cria uma nova tabela vazia
  while aberto:               #Enquanto o tempo simulado não houver chegado no limite o banco continua funcionando
        tipo = gera_tipo()
        gera_tempos(tipo)
        aberto = cria_tabela(tipo)
  calcula_media()
  for i in range(len(tempo_caixa)):
    tempo_caixa[i] = 0
    ocioso_caixa[i] = 0

media_media_desvio()
calcula_intervalo()

#print('Tempo médio gasto na fila =', media_fila)
#print('Tempo médio de serviço =', media_serviço)
#print('Tempo médio despendido no sistema =', media_sistema)
#print('Tempo médio ocioso do sistema =', media_ocioso)
#print()

print('Média das médias do tempo gasto na fila =', media_media_fila)
print('Média das médias do tempo de serviço =', media_media_serviço)
print('Média das médias do tempo despendido no sistema =', media_media_sistema)
print('Média das médias do tempo ocioso do sistema =', media_media_ocioso)
print()

print('Desvio padrão do tempo gasto na fila =', desvio_fila)
print('Desvio padrão do tempo de serviço =', desvio_serviço)
print('Desvio padrão do tempo despendido no sistema =', desvio_sistema)
print('Desvio padrão do tempo ocioso do sistema =', desvio_ocioso)
print()

print(f'Intervalo de confiança para o tempo gasto na fila = [{inferior_fila},{superior_fila}]')
print(f'Intervalo de confiança para o tempo de serviço = [{inferior_serviço},{superior_serviço}]')
print(f'Intervalo de confiança para o tempo despendido no sistema = [{inferior_sistema},{superior_sistema}]')
print(f'Intervalo de confiança para o tempo ocioso do sistema = [{inferior_ocioso},{superior_ocioso}]')